language: python
cache: pip

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - pytest -v --cov=urbansearch --cov-report term-missing tests/

after_success:
  - coveralls

