language: python
cache: pip

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - mkdir -p ~/.config/urbansearch
  - cp test_config.yml ~/.config/urbansearch/urbansearch.yml

script:
#  - pytest -v --cov=urbansearch --cov-report term-missing tests/
  - coverage run --source tests/ setup.py test

after_success:
  - coveralls

notifications:
  - email: never

