sudo: required
dist: trusty

language: python
cache:
  pip: true
  directories:
    - cache

python:
  - 3.5

env:
  - NEO4J_VERSION="3.1.4"

before_install:
  - jdk_switcher use oraclejdk8
  - mkdir -p cache

install:
  - if [ ! -f cache/neo4j-community-$NEO4J_VERSION-unix.tar.gz ]; then wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz -P cache; fi
  - tar -xzf cache/neo4j-community-$NEO4J_VERSION-unix.tar.gz -C .
  - neo4j-community-$NEO4J_VERSION/bin/neo4j-admin import --nodes:City test_neo4j_cities.csv
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - mkdir -p ~/.config/urbansearch
  - cp test_config.yml ~/.config/urbansearch/urbansearch.yml

script:
#  - pytest -v --cov=urbansearch --cov-report term-missing tests/
  - pytest --cov-report term-missing --cov urbansearch/ -v
#  - coverage run --source urbansearch/ setup.py test

after_success:
  - coveralls

notifications:
  - email: never

